blank_issues_enabled: false
contact_links:
    - name: 🤔 Questions and Help
      url: https://twittercommunity.com
      about: This issue tracker is not for support questions. Please use twittercommunity.com or the Discussions tab.
